# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d073cce4b6276998e375b325fcaa88083e195207a7f4086a104ae17ba997cfe87da02c9a71b9fed413a4ea018d2bfd2bf8080f55c3cb80f4366522f92174d42e

test:
  secret_key_base: 3365c928fca156c8eb0f6bd16331c1de84ddf5333746710a85597a0d99f3375b9467323f66f07c6587b9df8de6b873d802b0181fff450f1c8afe0c78d542a5a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
